# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
    test:
        desc: Test project
        cmds:
            - dotnet test -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml
            - dotnet ReportGenerator '-reporttypes:Html;TextSummary;MarkdownSummaryGithub' -reports:**/TestResults/coverage.cobertura.xml -targetdir:CoverageReport
            - cat CoverageReport/Summary.txt
        silent: true
